title:              BSS IT Technologies
email:              info@bss-it.kz
description:        Site of BSS IT Technologies company
author:             Dauren Amanbayev
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://daurenbss.github.io"

# Social Profiles
twitter_username:   bssit
github_username:    bssit
facebook_username:  bssit
linkedin_username:  bssit

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           3
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
